server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: root_password

  cache:
    type: redis
    redis:
      host: localhost
      port: 6379